# Generated by Django 3.2.5 on 2021-09-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='texts',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
